---
- hosts: localhost
  tasks:
    - dci_jobstate: 'Creating OSP 8 local mirrors and synchronizing them' status='pre-run'
    - include_vars: file='dci_session.yml' name='dci'
    - block:
      - name: Ensure proper directories are created
        file: path='{{ dci_mirror_location }}/{{ job_id }}' state="directory"
        with_items: "{{ dci['components'] }}"

      - name: Retrieve component
        dci_component:
          dest: '{{ dci_mirror_location }}/{{ item["id"] }}.tar'
          component_id: '{{ item["id"] }}'
        with_items: "{{ dci['components'] }}"

      - name: Unarchive component
        unarchive:
          src: '{{ dci_mirror_location }}/{{ item["id"] }}.tar'
          dest: '{{ dci_mirror_location }}/{{ job_id }}'
          remote_src: True
        with_items: "{{ dci['components'] }}"

      rescue:
      - name: Fail properly
        fail:
          msg: 'Something went wrong with the installation'
    - dci_jobstate: 'Spaning the undercloud' status='pre-run'
    - block:
      - include: pre-run.yml

      rescue:
      - name: Fail properly
        fail:
          msg: 'Something went wrong with the installation'
  - dci_jobstate: 'Provisioing the undercloud and the overcloud' status='pre-run'
  - block:
    - include: running.yml
    rescue:
    - name: Tear me down
      shell: echo 'Tear me down'

    - name: Fail properly
      fail:
        msg: 'Something went wrong with the installation'
    delegate_to: "{{ undercloud }}"
  - block:
    - name: Run tests
      dci_run_tests:
        undercloud_ip: '46.231.133.242'
        remoteci: 'dci-env-ovb-1'
        key_filename: '/root/.ssh/id_rsa'
        job_id: '{{ job_id }}'

    - name: Upload junit results
      dci_file:
        path: '{{ item.path }}'
        name: '{{ item.name }}'
           mime: 'application/junit'
           job_id: '{{ job_id }}'
         with_items:
           - {'name': 'Rally', 'path': 'rally.xml' }
           - {'name': 'Tempest', 'path': 'tempest.xml' }

      rescue:
      - name: Tear me down
        shell: echo 'Tear me down'

      - name: Fail properly
        fail:
          msg: 'Something went wrong with the installation'
    - dci_jobstate: status='success'
    - include: teardown.yml
